services:
  - type: static
    name: cds-frontend
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://cdsback-backend.onrender.com
